# Generated by Django 5.2.1 on 2025-05-20 08:22
from django.contrib.auth.models import BaseUserManager
from django.contrib.auth.hashers import make_password

from django.db import migrations


def init_backend_admin(apps, schema_editor):
    User = apps.get_model('users', 'User')
    AdminUser = apps.get_model('users', 'AdminUser')

    user = User()

    user.email = BaseUserManager.normalize_email('admin@example.com')
    user.password = make_password('Passw0rd!')
    user.is_staff = True
    user.is_superuser = True
    user.save()
    
    AdminUser.objects.create(
    user=user,
    role='manager',
    display_name='Admin User'
)

class Migration(migrations.Migration):
    

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(init_backend_admin)
    ]
