# Generated by Django 5.2.1 on 2025-07-12 04:58

from django.db import migrations
from django.contrib.auth.models import BaseUserManager
from django.contrib.auth.hashers import make_password

def init_backend_merchant(apps, schema_editor):
    User = apps.get_model('users', 'User')
    AdminUser = apps.get_model('users', 'AdminUser')

    user = User()

    user.email = BaseUserManager.normalize_email('merchant01@merchant.com')
    user.password = make_password('12345678')
    user.is_staff = True
    user.is_superuser = False
    user.save()
    
    AdminUser.objects.create(
    user=user,
    role='merchant',
    display_name='Merchant01 User'
)

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_init_backend_admin'),
    ]

    operations = [
        migrations.RunPython(init_backend_merchant)
    ]
