services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: tesddbusr
      POSTGRES_PASSWORD: tesddbpwd
      POSTGRES_DB: shopping_site
      DB_HOST: db
    # ports:
    #   - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U testuser']
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             pytest"
    environment:
      POSTGRES_USER: tesddbusr
      POSTGRES_PASSWORD: tesddbpwd
      POSTGRES_DB: shopping_site
      DB_HOST: db
    depends_on:
      db:
        condition: service_healthy
