services:
  backend:
    build: .
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - .:/app
    ports:
      - '8001:8001'
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  frontend:
    build:
      context: ./frontend
    ports:
      - '5174:5174'
    volumes:
      - ./frontend:/app
    command: npm run dev -- --host

volumes:
  postgres_data:
