# Generated by Django 5.2.1 on 2025-05-27 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='valid_until',
            new_name='valid_to',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='discount_amount',
        ),
        migrations.AddField(
            model_name='coupon',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coupon',
            name='discount_type',
            field=models.CharField(choices=[('percent', '百分比'), ('fixed', '固定金額')], default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coupon',
            name='discount_value',
            field=models.PositiveIntegerField(default=0, help_text='百分比填 10 表示 10%，固定金額填實際數值'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coupon',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='minimum_order_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='usage_limit',
            field=models.PositiveIntegerField(blank=True, help_text='可使用幾次（null 表示不限）', null=True),
        ),
    ]
