# Generated by Django 5.2.1 on 2025-06-11 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Init'), (10, 'Unpaid'), (11, 'Paid'), (20, 'Processing'), (21, 'Ready for pickup'), (22, 'Out of delivery'), (23, 'Delivered'), (90, 'Failed'), (91, 'Payment failed')], default=0),
        ),
    ]
