# Generated by Django 5.2.5 on 2025-09-03 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_address_order_phone_order_recipient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Init'), (10, 'Unpaid'), (11, 'Paid'), (20, 'Processing'), (21, 'Ready for pickup'), (22, 'Out of delivery'), (23, 'Delivered'), (90, 'Failed'), (91, 'Payment failed'), (95, 'Returned'), (96, 'Exchanged'), (99, 'Cancelled')], default=0),
        ),
    ]
