name: Local Docker CI/CD

on:
  push:
    branches: ['develop', 'main']
  pull_request:
    branches: ['develop', 'main']

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: '!QAZ2wsx#EDC'
          POSTGRES_DB: shopping_site
        ports: []
        options: >-
          --health-cmd="pg_isready -U admin"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run migrations
        env:
          DATABASE_URL: postgres://admin:!QAZ2wsx%23EDC@postgres:5432/shopping_site
        run: python manage.py migrate

      - name: Run tests
        env:
          DATABASE_URL: postgres://admin:!QAZ2wsx%23EDC@postgres:5432/shopping_site
        run: pytest

  # docker-build:
  #   runs-on: ubuntu-latest
  #   needs: build-test
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Build Docker image
  #       run: docker build -t myapp:${{ github.sha }} .
