# Generated by Django 5.2.1 on 2025-06-12 03:22

from django.db import migrations

def insert_product_category(apps, schema_editor):
    ProductCategory = apps.get_model('products','ProductCategory')
    category_names = [ "相機","電腦","手機","平板","藍芽耳機","滑鼠","鍵盤","SSD","螢幕","智慧手錶"]

    create_list = []
    for category_name in category_names:
        create_list.append(ProductCategory(name=category_name))
    ProductCategory.objects.bulk_create(create_list)


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_created_at_product_updated_at'),
    ]

    operations = [
        migrations.RunPython(insert_product_category)
    ]
